# Generated by Django 5.0 on 2026-04-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Asset",
        ),
    ]
