# Generated by Django 5.0 on 2025-11-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_asset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BtcPrice',
        ),
    ]
