# Generated by Django 5.0 on 2026-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtest",
            name="timeframe",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
