# Generated by Django 5.0 on 2026-03-11 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtests", "0002_backtest_timeframe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trade",
            old_name="price",
            new_name="entry_price",
        ),
        migrations.RenameField(
            model_name="trade",
            old_name="time",
            new_name="entry_time",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="is_buy",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="profit",
        ),
        migrations.AddField(
            model_name="trade",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trade",
            name="exit_price",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="exit_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="result",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="profit or loss",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="status",
            field=models.CharField(
                blank=True, help_text="open / closed", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="stop_loss",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="take_profit",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(default=1, help_text="buy or sell", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trade",
            name="quantity",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
