# Generated by Django 5.0 on 2025-10-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0002_asset_backtest_trade_delete_backtestprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterModelTable(
            name='asset',
            table=None,
        ),
    ]
