# Generated by Django 5.0 on 2025-12-15 15:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0003_trades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trades',
            new_name='Trade',
        ),
    ]
