# Generated by Django 5.0 on 2026-03-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0003_rename_price_trade_entry_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='candles_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
