# Generated by Django 5.0 on 2025-12-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0004_rename_trades_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='Backtest',
        ),
        migrations.AddField(
            model_name='trade',
            name='backtest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtests.backtest'),
        ),
    ]
