# Generated by Django 5.0 on 2026-04-20 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtests", "0004_backtest_candles_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backtest",
            name="position_size",
        ),
        migrations.AlterField(
            model_name="backtest",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="backtest",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 20, 8, 43, 52, 862170, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
