# Generated by Django 5.0 on 2025-12-28 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0005_remove_trade_backtest_trade_backtest'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtest',
            name='price',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='time',
        ),
        migrations.AddField(
            model_name='backtest',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backtests.asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backtest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='initial_capital',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='position_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='strategy',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='is_buy',
            field=models.BooleanField(default=True, help_text='True = BUY, False = SELL'),
            preserve_default=False,
        ),
    ]
