from apps.strategies.services.atomic_strategies.rsi_strategy import RSIStrategy
from apps.strategies.services.atomic_strategies.sma_strategy import SMAStrategy
from apps.strategies.services.atomic_strategies.arima_strategy import ARIMAStrategy
from apps.strategies.services.atomic_strategies.macd_strategy import MACDStrategy